void handleCss()
{
  server.send(200, "text/css", css());
}

String header() {
  String content = "<head><title>Ethernet Switchbox</title>\n<meta name=\"description\" content=\"Ethetnet Switchbox\"/>";
  content += "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n";
  content += "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"default\">\n";
  content += "<meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n";
  content += "<link rel=\"stylesheet\" href=\"style.css\">";
  return content;
}

String css()
{
  String output = " html { height:100%; }\n";
  output += "body {\n";
  output += "      height: 100%;\n";
  output += "      margin: 0;\n";
  output += "      font-family: helvetica, sans-serif;\n";
  output += "      -webkit-text-size-adjust: none;\n";
  output += "     }\n\n";
  output += "  body {\n";
  output += "      -webkit-background-size: 100% 21px;\n";
  output += "      background-color: #c5bcd3;\n";
  output += "      background-image:\n";
  output += "      -webkit-gradient(linear, left top, right top,\n";
  output += "      color-stop(.75, transparent),\n";
  output += "      color-stop(.75, rgba(255,255,255,.1)) );\n";
  output += "      -webkit-background-size: 7px;\n";
  output += "     }\n";
  output += " .view {\n      min-height: 100%;\n      overflow: auto;\n     }\n";
  output += "  .header-wrapper {\n";
  output += "      height: 44px;\n";
  output += "      font-weight: bold;\n";
  output += "      text-shadow: rgba(0,0,0,0.7) 0 -1px 0;\n";
  output += "      border-top: solid 1px rgba(255,255,255,0.6);\n";
  output += "      border-bottom: solid 1px rgba(0,0,0,0.6);\n";
  output += "      color: #fff;\n";
  output += "      background-color: #8195af;\n";
  output += "      background-image:\n";
  output += "      -webkit-gradient(linear, left top, left bottom,\n";
  output += "      from(rgba(255,255,255,.4)),\n";
  output += "      to(rgba(255,255,255,.05)) ),\n";
  output += "      -webkit-gradient(linear, left top, left bottom,\n";
  output += "      from(transparent),\n";
  output += "      to(rgba(0,0,64,.1)) );\n";
  output += "      background-repeat: no-repeat;\n";
  output += "      background-position: top left, bottom left;\n";
  output += "      -webkit-background-size: 100% 21px, 100% 22px;\n";
  output += "      -webkit-box-sizing: border-box;\n";
  output += "     }\n";
  output += "  .header-wrapper h1 {\n";
  output += "      text-align: center;\n";
  output += "      font-size: 20px;\n";
  output += "      line-height: 44px;\n";
  output += "      margin: 0;\n";
  output += "     }\n";
  output += "  .group-wrapper {\n      margin: 9px;\n      }\n";
  output += "  .group-wrapper h2 {\n";
  output += "      color: #4c566c;\n";
  output += "      font-size: 17px;\n";
  output += "      line-height: 0.8;\n";
  output += "      font-weight: bold;\n";
  output += "      text-shadow: #fff 0 1px 0;n";
  output += "      margin: 20px 10px 12px;\n";
  output += "     }\n";
  output += "  .group-wrapper h3 {\n";
  output += "      color: #4c566c;\n";
  output += "      font-size: 12px;\n";
  output += "      line-height: 1;\n";
  output += "      font-weight: bold;\n";
  output += "      text-shadow: #fff 0 1px 0;\n";
  output += "      margin: 20px 10px 12px;\n";
  output += "     }\n";
  output += "  .group-wrapper h4 { \n";
  output += "      color: #212121;\n";
  output += "      font-size: 14px;\n";
  output += "      line-height: 1;n";
  output += "      font-weight: bold;\n";
  output += "      text-shadow: #aaa 1px 1px 3px;\n";
  output += "      margin: 5px 5px 5px;\n";
  output += "     }\n";
  output += "  .group-wrapper table {\n";
  output += "      background-color: #fff;\n";
  output += "      -webkit-border-radius: 10px;\n";
  output += "      -moz-border-radius: 10px;\n";
  output += "      -khtml-border-radius: 10px;\n";
  output += "      border-radius: 10px;\n";
  output += "      font-size: 17px;\n";
  output += "      line-height: 20px;\n";
  output += "      margin: 9px 0 20px;\n";
  output += "      border: solid 1px #a9abae;\n";
  output += "      padding: 11px 3px 12px 3px;\n";
  output += "      margin-left:auto;\n";
  output += "      margin-right:auto;n";
  output += "      -moz-transform :scale(1); \n";
  output += "      -moz-transform-origin: 0 0;\n";
  output += "      -moz-transform-origin: 0 0;n";
  output += "     }\n";
  output += "  table {\n";
  output += "      background-color: #fff;\n";
  output += "      -webkit-border-radius: 10px;\n";
  output += "      -moz-border-radius: 10px;\n";
  output += "      -khtml-border-radius: 10px;\n";
  output += "      border-radius: 10px;\n";
  output += "      font-size: 17px;\n";
  output += "      line-height: 20px;\n";
  output += "      margin: 9px 0 20px;\n";
  output += "      border: solid 1px #a9abae;\n";
  output += "      padding: 11px 3px 12px 3px;\n";
  output += "      margin-left:auto;\n";
  output += "      margin-right:auto;n";
  output += "      -moz-transform :scale(1); \n";
  output += "      -moz-transform-origin: 0 0;\n";
  output += "      -moz-transform-origin: 0 0;n";
  output += "     }\n";
  output += "  .green-circle {\n";
  output += "      display: block;\n";
  output += "      height: 23px;\n      width: 23px;\n";
  output += "      background-color: #0f0;\n";
  output += "      -moz-border-radius: 11px;\n";
  output += "      -webkit-border-radius: 11px;\n";
  output += "      -khtml-border-radius: 11px;\n";
  output += "      border-radius: 11px;\n";
  output += "      margin-left: 1px;\n";
  output += "      background-image: -webkit-gradient(linear, 0% 0%, 0% 90%, from(rgba(46, 184, 0, 0.8)), to(rgba(148, 255, 112, .9)));@\n";
  output += "      border: 2px solid #ccc;\n";
  output += "      -webkit-box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px;\n";
  output += "      -moz-box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px;n";
  output += "      box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px; \n";
  output += "      }\n";
  output += "  .black-circle {\n";
  output += "      display: block;\n      height: 23px;\n      width: 23px;\n";
  output += "      background-color: #040;\n";
  output += "      -moz-border-radius: 11px;\n";
  output += "      -webkit-border-radius: 11px;n";
  output += "      -khtml-border-radius: 11px;\n";
  output += "      border-radius: 11px;\n";
  output += "      margin-left: 1px;\n";
  output += "      -webkit-box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px;\n";
  output += "      -moz-box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px; \n";
  output += "      box-shadow: rgba(11, 140, 27, 0.5) 0px 10px 16px;\n";
  output += "      }\n";
  output += "     .glare {\n";
  output += "        position: relative;\n";
  output += "        top: 1;\n        left: 5px;\n";
  output += "        -webkit-border-radius: 10px;\n";
  output += "        -moz-border-radius: 10px;\n";
  output += "        -khtml-border-radius: 10px;\n";
  output += "        border-radius: 10px;\n";
  output += "        height: 1px;\n";
  output += "        width: 13px;\n";
  output += "        padding: 5px 0;\n";
  output += "        background-color: rgba(200, 200, 200, 0.25);\n";
  output += "        background-image: -webkit-gradient(linear, 0% 0%, 0% 95%, from(rgba(255, 255, 255, 0.7)), to(rgba(255, 255, 255, 0)));\n";
  output += "      }\n";

  return output;
}

